language: scala
scala:
  - 2.13.3
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
before_install:
  - git fetch --tags
stages:
  - name: test
  - name: release
    if: (tag IS present) AND NOT fork
jobs:
  include:
    - name: compile
      script: sbt ++$TRAVIS_SCALA_VERSION compile test:compile
    - name: formatting
      script: ./bin/scalafmt --test
    - stage: release
      script: sbt ci-release
